#include "qihse_qql_parser.h"
#include <stdio.h>
#include <string.h>
#include <tree_sitter/api.h>
#include <stdlib.h>

#ifdef _WIN32
#include <windows.h>
static uint64_t parser_get_time_ms(void) {
    return GetTickCount64();
}
#else
#include <sys/time.h>
static uint64_t parser_get_time_ms(void) {
    struct timeval tv;
    gettimeofday(&tv, NULL);
    return (uint64_t)(tv.tv_sec) * 1000 + (uint64_t)(tv.tv_usec) / 1000;
}
#endif

typedef struct {
    const char *string;
    uint32_t length;
} QQLStringInput;

static const char *qql_read_callback(void *payload, uint32_t byte_index, TSPoint position, uint32_t *bytes_read) {
    (void)position;
    QQLStringInput *input = (QQLStringInput *)payload;
    if (byte_index >= input->length) {
        *bytes_read = 0;
        return "";
    }
    *bytes_read = input->length - byte_index;
    return input->string + byte_index;
}

static bool qql_progress_callback(TSParseState *state) {
    if (!state || !state->payload) return false;
    uint64_t* start_time = (uint64_t*)state->payload;
    uint64_t now = parser_get_time_ms();
    if (now - *start_time > 10) { // 10ms strict timeout for DoS prevention
        return true; 
    }
    return false;
}

// Declare the external language function generated by tree-sitter
TSLanguage *tree_sitter_qql(void);

#define QIHSE_QQL_MAX_LENGTH 1024

qihse_qql_ast_t* qihse_parse_qql_to_ast(const char* qql) {
    if (!qql) {
        return NULL;
    }

    size_t qql_len = strlen(qql);
    if (qql_len > QIHSE_QQL_MAX_LENGTH) {
        fprintf(stderr, "[Security] QQL Parser rejected query: exceeds maximum size limit of %d bytes.\n", QIHSE_QQL_MAX_LENGTH);
        return NULL;
    }

    // printf("Tokenizing QQL string: %s\n", qql);

    qihse_qql_ast_t* ast = calloc(1, sizeof(qihse_qql_ast_t));
    if (!ast) return NULL;

    
    // Initialize the Tree-sitter parser
    TSParser *parser = ts_parser_new();
    ts_parser_set_language(parser, tree_sitter_qql());

    uint64_t start_time = parser_get_time_ms();
    TSParseOptions options = {
        .payload = &start_time,
        .progress_callback = qql_progress_callback
    };

    QQLStringInput string_input = {qql, qql_len};
    TSInput input = {
        .payload = &string_input,
        .read = qql_read_callback,
        .encoding = TSInputEncodingUTF8,
        .decode = NULL
    };

    // Parse the query string into an AST with a timeout
    TSTree *tree = ts_parser_parse_with_options(
        parser,
        NULL,
        input,
        options
    );

    if (!tree) {
        printf("[Security] QQL Parser aborted: query exceeded maximum execution time (10ms) or syntax was fatally malformed.\n");
        ts_parser_delete(parser);
        free(ast);
        return NULL;
    }

    // Get the root node of the syntax tree
    TSNode root_node = ts_tree_root_node(tree);
    
    // Convert to S-expression string to display the parsed AST
    char *string = ts_node_string(root_node);
    // printf("QQL AST Generated: %s\n", string);
    
    if (strstr(string, "(ERROR")) {
        free(string);
        ts_tree_delete(tree);
        ts_parser_delete(parser);
        free(ast);
        return NULL;
    }
    
    // Free the string allocated by ts_node_string
    free(string);

    // Traverse root_node and map it
    uint32_t num_children = ts_node_child_count(root_node);
    for (uint32_t i = 0; i < num_children; i++) {
        TSNode stmt_node = ts_node_child(root_node, i);
        if (strcmp(ts_node_type(stmt_node), "statement") != 0) continue;
        
        TSNode node = ts_node_child(stmt_node, 0);
        const char* type = ts_node_type(node);
        
        if (strcmp(type, "search_statement") == 0) {
            
            TSNode table_node = ts_node_child_by_field_name(node, "table", 5);
            if (!ts_node_is_null(table_node)) {
                uint32_t start = ts_node_start_byte(table_node);
                uint32_t len = ts_node_end_byte(table_node) - start;
                strncpy(ast->table_name, qql + start, len < 255 ? len : 255);
            }
            
            TSNode limit_node = ts_node_child_by_field_name(node, "limit", 5);
            ast->limit = 10;
            if (!ts_node_is_null(limit_node)) {
                uint32_t l_start = ts_node_start_byte(limit_node);
                uint32_t l_len = ts_node_end_byte(limit_node) - l_start;
                char limit_str[32] = {0};
                strncpy(limit_str, qql + l_start, l_len < 31 ? l_len : 31);
                ast->limit = (int)strtol(limit_str, NULL, 10);
                if (ast->limit < 0) ast->limit = 10;
            }
            
            // Parse temporal clause
            TSNode temporal_node = ts_node_child_by_field_name(node, "temporal", 8);
            if (!ts_node_is_null(temporal_node)) {
                TSNode start_time = ts_node_child_by_field_name(temporal_node, "start_time", 10);
                TSNode end_time = ts_node_child_by_field_name(temporal_node, "end_time", 8);
                if (!ts_node_is_null(start_time) && !ts_node_is_null(end_time)) {
                    ast->has_temporal = 1;
                    uint32_t st_s = ts_node_start_byte(start_time), st_l = ts_node_end_byte(start_time) - st_s;
                    uint32_t et_s = ts_node_start_byte(end_time), et_l = ts_node_end_byte(end_time) - et_s;
                    strncpy(ast->start_time, qql + st_s, st_l < 63 ? st_l : 63);
                    strncpy(ast->end_time, qql + et_s, et_l < 63 ? et_l : 63);
                }
            }
            
            // Parse spatial clause
            TSNode spatial_node = ts_node_child_by_field_name(node, "spatial", 7);
            if (!ts_node_is_null(spatial_node)) {
                TSNode radius = ts_node_child_by_field_name(spatial_node, "radius", 6);
                TSNode lat = ts_node_child_by_field_name(spatial_node, "lat", 3);
                TSNode lon = ts_node_child_by_field_name(spatial_node, "lon", 3);
                if (!ts_node_is_null(radius) && !ts_node_is_null(lat) && !ts_node_is_null(lon)) {
                    ast->has_spatial = 1;
                    char r_str[32] = {0}, lat_str[32] = {0}, lon_str[32] = {0};
                    uint32_t rs = ts_node_start_byte(radius), rl = ts_node_end_byte(radius) - rs;
                    uint32_t lats = ts_node_start_byte(lat), latl = ts_node_end_byte(lat) - lats;
                    uint32_t lons = ts_node_start_byte(lon), lonl = ts_node_end_byte(lon) - lons;
                    strncpy(r_str, qql + rs, rl < 31 ? rl : 31);
                    strncpy(lat_str, qql + lats, latl < 31 ? latl : 31);
                    strncpy(lon_str, qql + lons, lonl < 31 ? lonl : 31);
                    ast->radius = strtod(r_str, NULL);
                    ast->lat = strtod(lat_str, NULL);
                    ast->lon = strtod(lon_str, NULL);
                }
            }
            
            // Parse Join clause
            TSNode join_node = ts_node_child_by_field_name(node, "join_table", 10);
            if (!ts_node_is_null(join_node)) {
                TSNode join_left = ts_node_child_by_field_name(node, "join_left", 9);
                TSNode join_right = ts_node_child_by_field_name(node, "join_right", 10);
                if (!ts_node_is_null(join_left) && !ts_node_is_null(join_right)) {
                    ast->has_join = 1;
                    uint32_t jts = ts_node_start_byte(join_node), jtl = ts_node_end_byte(join_node) - jts;
                    uint32_t jls = ts_node_start_byte(join_left), jll = ts_node_end_byte(join_left) - jls;
                    uint32_t jrs = ts_node_start_byte(join_right), jrl = ts_node_end_byte(join_right) - jrs;
                    strncpy(ast->join_table, qql + jts, jtl < 63 ? jtl : 63);
                    strncpy(ast->join_left, qql + jls, jll < 63 ? jll : 63);
                    strncpy(ast->join_right, qql + jrs, jrl < 63 ? jrl : 63);
                }
            }

            TSNode vector_node = ts_node_child_by_field_name(node, "vector", 6);
            if (!ts_node_is_null(vector_node)) {
                ast->is_vector_search = 1;
            } else {
                TSNode string_node = ts_node_child_by_field_name(node, "query_string", 12);
                if (!ts_node_is_null(string_node)) {
                    ast->is_text_search = 1;
                    uint32_t s_start = ts_node_start_byte(string_node);
                    uint32_t s_len = ts_node_end_byte(string_node) - s_start;
                    strncpy(ast->query_string, qql + s_start, s_len < 255 ? s_len : 255);
                }
            }

        } else if (strcmp(type, "insert_statement") == 0) {
            TSNode table_node = ts_node_child_by_field_name(node, "table", 5);
            char table_name[256] = {0};
            if (!ts_node_is_null(table_node)) {
                uint32_t start = ts_node_start_byte(table_node);
                uint32_t len = ts_node_end_byte(table_node) - start;
                strncpy(table_name, qql + start, len < 255 ? len : 255);
            }
            
            TSNode val1_node = ts_node_child_by_field_name(node, "val1", 4);
            TSNode val2_node = ts_node_child_by_field_name(node, "val2", 4);
            
            char v1[256] = {0}; char v2[256] = {0};
            if (!ts_node_is_null(val1_node)) {
                uint32_t s1 = ts_node_start_byte(val1_node); uint32_t l1 = ts_node_end_byte(val1_node) - s1;
                strncpy(v1, qql + s1, l1 < 255 ? l1 : 255);
            }
            if (!ts_node_is_null(val2_node)) {
                uint32_t s2 = ts_node_start_byte(val2_node); uint32_t l2 = ts_node_end_byte(val2_node) - s2;
                strncpy(v2, qql + s2, l2 < 255 ? l2 : 255);
            }
            
            printf("=> [EXECUTE] qihse_kv_set on table '%s' (KEY: %s, VAL: %s)\n", table_name, v1, v2);
        }
    }

    ts_tree_delete(tree);
    ts_parser_delete(parser);

    return ast;
}
